
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('investors').del()
    .then(function () {
      // Inserts seed entries
      return knex('investors').insert([
        {name: 'Nathan Norberg', emailAndLogin: 'nathan@g.com', confirmPassword: 'asdf', password: 'asdf', address: '33620 Orlinda Dr', city: 'Temecula', state: 'California', contactNumber: '111-111-1111', mobileNumber: '111-111-1111', status: 'Active', notesForInvestors: 'Super Dope dude with lots of money'},
        {name: 'Mike Norberg', emailAndLogin: 'mike@g.com', confirmPassword: 'asdf', password: 'asdf', address: '6750 Fig St', city: 'Riverside', state: 'California', contactNumber: '222-222-2222', mobileNumber: '222-222-2222', status: 'Inactive', notesForInvestors: 'Spends money all the time.  Likes to actively participate in investments.'},
        {name: 'Mindy Norberg', emailAndLogin: 'mindy@g.com', confirmPassword: 'asdf', password: 'asdf', address: '3033 E Siesta Ln', city: 'Phoenix', state: 'Arizona', contactNumber: '333-333-3333', mobileNumber: '333-333-3333', status: 'Active', notesForInvestors: 'Likes to invest in medical stuffs'},
        {name: 'Justin Beiber', emailAndLogin: 'justin@g.com', confirmPassword: 'asdf', password: 'asdf', address: '7840 W Freedline Dr', city: 'Flagstaff', state: 'Arizona', contactNumber: '444-444-4444', mobileNumber: '4444-444-4444', status: 'Active', notesForInvestors: 'Big fan of investing in media and music.'},
        {name: 'Kevin Durant', emailAndLogin: 'kevin@g.com', confirmPassword: 'asdf', password: 'asdf', address: '2511 Palmera Dr', city: 'Paradise', state: 'Nevada', contactNumber: '555-555-5555', mobileNumber: '555-555-5555', status: 'Active', notesForInvestors: 'This is a werido'},
        {name: 'Derek Hough', emailAndLogin: 'derek@g.com', confirmPassword: 'asdf', password: 'asdf', address: '135 Kava Kava St', city: 'Henderson', state: 'Nevada', contactNumber: '666-666-6666', mobileNumber: '666-666-6666', status: 'Inactive', notesForInvestors: 'I cannot stand him'},
        {name: 'Thomas Brady', emailAndLogin: 'thomas@g.com', confirmPassword: 'asdf', password: 'asdf', address: '2981 Blueberry Cir', city: 'St George', state: 'Utah', contactNumber: '777-777-7777', mobileNumber: '777-777-7777', status: 'Active', notesForInvestors: 'Will invest in any project we present'},
        {name: 'Jack Black', emailAndLogin: 'jack@g.com', confirmPassword: 'asdf', password: 'asdf', address: '1978 L St', city: 'Springfield', state: 'Oregon', contactNumber: '888-888-8888', mobileNumber: '888-888-8888', status: 'Active', notesForInvestors: 'Likes to invest in medical stuffs'},
        {name: 'Ellen Degeneres', emailAndLogin: 'ellen@g.com', confirmPassword: 'asdf', password: 'asdf', address: '2200 W Bannock Rd', city: 'Jackson', state: 'Wyoming', contactNumber: '999-999-9999', mobileNumber: '999-999-9999', status: 'Inactive', notesForInvestors: 'Likes to invest in medical stuffs'},
        {name: 'Jennifer Lopez', emailAndLogin: 'jennifer@g.com', confirmPassword: 'asdf', password: 'asdf', address: '258 E Coatsville Ave', city: 'Salt Lake City', state: 'Utah', contactNumber: '000-000-0000', mobileNumber: '000-000-0000', status: 'Active', notesForInvestors: 'Likes to invest in medical stuffs'},
        {name: 'Kimberly Kardashian', emailAndLogin: 'kimberly@g.com', confirmPassword: 'asdf', password: 'asdf', address: '1469 Fillmore St', city: 'Denver', state: 'Colorado', contactNumber: '111-111-1111', mobileNumber: '111-111-1111', status: 'Active', notesForInvestors: 'Likes to invest in medical stuffs'},
        {name: 'Simon Cowell', emailAndLogin: 'simon@g.com', confirmPassword: 'asdf', password: 'asdf', address: '105 Edelweiss', city: 'Tijeras', state: 'New Mexico', contactNumber: '222-222-2222', mobileNumber: '222-222-2222', status: 'Inactive', notesForInvestors: 'Likes to invest in medical stuffs'},
        {name: 'Terry Crews', emailAndLogin: 'terry@g.com', confirmPassword: 'asdf', password: 'asdf', address: '409 E 86th St', city: 'Odessa', state: 'Texas', contactNumber: '333-333-3333', mobileNumber: '333-333-3333', status: 'Active', notesForInvestors: 'Likes to invest in medical stuffs'},
        {name: 'Rocky Balboa', emailAndLogin: 'rocky@g.com', confirmPassword: 'asdf', password: 'asdf', address: '358 Mesa Grande Dr', city: 'Fort Worth', state: 'Texas', contactNumber: '444-444-4444', mobileNumber: '444-444-4444', status: 'Active', notesForInvestors: 'Likes to invest in medical stuffs'},
        {name: 'Matthew Murdock', emailAndLogin: 'matthew@g.com', confirmPassword: 'asdf', password: 'asdf', address: '106 Holborn Ct', city: 'Columbia', state: 'South Carolina', contactNumber: '555-555-5555', mobileNumber: '555-555-5555', status: 'Active', notesForInvestors: 'Likes to invest in medical stuffs'},
        {name: 'Jessica Jones', emailAndLogin: 'jessica@g.com', confirmPassword: 'asdf', password: 'asdf', address: '6702 Buffalo Ave', city: 'Jacksonville', state: 'Florida', contactNumber: '666-666-6666', mobileNumber: '666-666-6666', status: 'Inactive', notesForInvestors: 'Likes to invest in medical stuffs'},
        {name: 'Daniel Rand', emailAndLogin: 'daniel@g.com', confirmPassword: 'asdf', password: 'asdf', address: '6516 Lincoln Dr', city: 'Philadelphia', state: 'DescriptionPennsylvania', contactNumber: '777-777-7777', mobileNumber: '777-777-7777', status: 'Active', notesForInvestors: 'Likes to invest in medical stuffs'},
        {name: 'Frank Castle', emailAndLogin: 'frank@g.com', confirmPassword: 'asdf', password: 'asdf', address: '12 Oakridge Dr', city: 'Huntington', state: 'New York', contactNumber: '888-888-8888', mobileNumber: '888-888-8888', status: 'Active', notesForInvestors: 'Likes to invest in medical stuffs'},
      ]);
    });
};
