
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('investorEntities').del()
    .then(function () {
      // Inserts seed entries
      return knex('investorEntities').insert([
        {investor_id: 1, name: 'Nathan Norberg', address: '33620 Orlinda Dr', city: 'Temecula', state: 'California', contactNumber: '111-111-1111', mobileNumber: '111-111-1111', entityNotes: 'This entity is through them personally, not any other company'},
        {investor_id: 1, name: 'Nugman', address: '33620 Orlinda Dr', city: 'Temecula', state: 'California', contactNumber: '111-111-1111', mobileNumber: '111-111-1111', entityNotes: 'This is the investors primary entity that they will invest through. Also their primary business.'},
        {investor_id: 2, name: 'Mike Norberg', address: '6750 Fig St', city: 'Riverside', state: 'California', contactNumber: '222-222-2222', mobileNumber: '222-222-2222', entityNotes: 'This entity is through them personally, not any other company'},
        {investor_id: 2, name: 'White Mamba', address: '6750 Fig St', city: 'Riverside', state: 'California', contactNumber: '222-222-2222', mobileNumber: '222-222-2222', entityNotes: 'This is the investors primary entity that they will invest through. Also their primary business.'},
        {investor_id: 3, name: 'Mindy Norberg', address: '3033 E Siesta Ln', city: 'Phoenix', state: 'Arizona', contactNumber: '333-333-3333', mobileNumber: '333-333-3333', entityNotes: 'This entity is through them personally, not any other company'},
        {investor_id: 3, name: 'Nuses101', address: '3033 E Siesta Ln', city: 'Phoenix', state: 'Arizona', contactNumber: '333-333-3333', mobileNumber: '333-333-3333', entityNotes: 'This is the investors primary entity that they will invest through. Also their primary business.'},
        {investor_id: 4, name: 'Justin Beiber', address: '7840 W Freedline Dr', city: 'Flagstaff', state: 'Arizona', contactNumber: '444-444-4444', mobileNumber: '4444-444-4444', entityNotes: 'This entity is through them personally, not any other company'},
        {investor_id: 4, name: 'Beliebers', address: '7840 W Freedline Dr', city: 'Flagstaff', state: 'Arizona', contactNumber: '444-444-4444', mobileNumber: '4444-444-4444', entityNotes: 'This is the investors primary entity that they will invest through. Also their primary business.'},
        {investor_id: 5, name: 'Kevin Durant', address: '2511 Palmera Dr', city: 'Paradise', state: 'Nevada', contactNumber: '555-555-5555', mobileNumber: '555-555-5555', entityNotes: 'This entity is through them personally, not any other company'},
        {investor_id: 5, name: 'Team Hoppers', address: '2511 Palmera Dr', city: 'Paradise', state: 'Nevada', contactNumber: '555-555-5555', mobileNumber: '555-555-5555', entityNotes: 'This is the investors primary entity that they will invest through. Also their primary business.'},
        {investor_id: 6, name: 'Derek Hough', address: '135 Kava Kava St', city: 'Henderson', state: 'Nevada', contactNumber: '666-666-6666', mobileNumber: '666-666-6666', entityNotes: 'This entity is through them personally, not any other company'},
        {investor_id: 6, name: 'Cha Cha Cha', address: '135 Kava Kava St', city: 'Henderson', state: 'Nevada', contactNumber: '666-666-6666', mobileNumber: '666-666-6666', entityNotes: 'This is the investors primary entity that they will invest through. Also their primary business.'},
        {investor_id: 7, name: 'Thomas Brady', address: '2981 Blueberry Cir', city: 'St George', state: 'Utah', contactNumber: '777-777-7777', mobileNumber: '777-777-7777', entityNotes: 'This entity is through them personally, not any other company'},
        {investor_id: 7, name: 'DeflateMe', address: '2981 Blueberry Cir', city: 'St George', state: 'Utah', contactNumber: '777-777-7777', mobileNumber: '777-777-7777', entityNotes: 'This is the investors primary entity that they will invest through. Also their primary business.'},
        {investor_id: 8, name: 'Jack Black', address: '1978 L St', city: 'Springfield', state: 'Oregon', contactNumber: '888-888-8888', mobileNumber: '888-888-8888', entityNotes: 'This entity is through them personally, not any other company'},
        {investor_id: 8, name: 'School of Rock', address: '1978 L St', city: 'Springfield', state: 'Oregon', contactNumber: '888-888-8888', mobileNumber: '888-888-8888', entityNotes: 'This is the investors primary entity that they will invest through. Also their primary business.'},
        {investor_id: 9, name: 'Ellen Degeneres', address: '2200 W Bannock Rd', city: 'Jackson', state: 'Wyoming', contactNumber: '999-999-9999', mobileNumber: '999-999-9999', entityNotes: 'This entity is through them personally, not any other company'},
        {investor_id: 9, name: 'Game of Games', address: '2200 W Bannock Rd', city: 'Jackson', state: 'Wyoming', contactNumber: '999-999-9999', mobileNumber: '999-999-9999', entityNotes: 'This is the investors primary entity that they will invest through. Also their primary business.'},
        {investor_id: 10, name: 'Jennifer Lopez', address: '258 E Coatsville Ave', city: 'Salt Lake City', state: 'Utah', contactNumber: '000-000-0000', mobileNumber: '000-000-0000', entityNotes: 'This entity is through them personally, not any other company'},
        {investor_id: 10, name: 'World of Dance', address: '258 E Coatsville Ave', city: 'Salt Lake City', state: 'Utah', contactNumber: '000-000-0000', mobileNumber: '000-000-0000', entityNotes: 'This is the investors primary entity that they will invest through. Also their primary business.'},
        {investor_id: 11, name: 'Kimberly Kardashian', address: '1469 Fillmore St', city: 'Denver', state: 'Colorado', contactNumber: '111-111-1111', mobileNumber: '111-111-1111', entityNotes: 'This entity is through them personally, not any other company'},
        {investor_id: 11, name: 'Big Butts Galore', address: '1469 Fillmore St', city: 'Denver', state: 'Colorado', contactNumber: '111-111-1111', mobileNumber: '111-111-1111', entityNotes: 'This is the investors primary entity that they will invest through. Also their primary business.'},
        {investor_id: 12, name: 'Simon Cowell', address: '105 Edelweiss', city: 'Tijeras', state: 'New Mexico', contactNumber: '222-222-2222', mobileNumber: '222-222-2222', entityNotes: 'This entity is through them personally, not any other company'},
        {investor_id: 12, name: 'AGT', address: '105 Edelweiss', city: 'Tijeras', state: 'New Mexico', contactNumber: '222-222-2222', mobileNumber: '222-222-2222', entityNotes: 'This is the investors primary entity that they will invest through. Also their primary business.'},
        {investor_id: 13, name: 'Terry Crews', address: '409 E 86th St', city: 'Odessa', state: 'Texas', contactNumber: '333-333-3333', mobileNumber: '333-333-3333', entityNotes: 'This entity is through them personally, not any other company'},
        {investor_id: 13, name: 'PecCity', address: '409 E 86th St', city: 'Odessa', state: 'Texas', contactNumber: '333-333-3333', mobileNumber: '333-333-3333', entityNotes: 'This is the investors primary entity that they will invest through. Also their primary business.'},
        {investor_id: 14, name: 'Rocky Balboa', address: '358 Mesa Grande Dr', city: 'Fort Worth', state: 'Texas', contactNumber: '444-444-4444', mobileNumber: '444-444-4444', entityNotes: 'This entity is through them personally, not any other company'},
        {investor_id: 14, name: 'Adrian', address: '358 Mesa Grande Dr', city: 'Fort Worth', state: 'Texas', contactNumber: '444-444-4444', mobileNumber: '444-444-4444', entityNotes: 'This is the investors primary entity that they will invest through. Also their primary business.'},
        {investor_id: 15, name: 'Matthew Murdock', address: '106 Holborn Ct', city: 'Columbia', state: 'South Carolina', contactNumber: '555-555-5555', mobileNumber: '555-555-5555', entityNotes: 'This entity is through them personally, not any other company'},
        {investor_id: 15, name: 'Daredevil', address: '106 Holborn Ct', city: 'Columbia', state: 'South Carolina', contactNumber: '555-555-5555', mobileNumber: '555-555-5555', entityNotes: 'This is the investors primary entity that they will invest through. Also their primary business.'},
        {investor_id: 16, name: 'Jessica Jones', address: '6702 Buffalo Ave', city: 'Jacksonville', state: 'Florida', contactNumber: '666-666-6666', mobileNumber: '666-666-6666', entityNotes: 'This entity is through them personally, not any other company'},
        {investor_id: 16, name: 'Investigators4Hire', address: '6702 Buffalo Ave', city: 'Jacksonville', state: 'Florida', contactNumber: '666-666-6666', mobileNumber: '666-666-6666', entityNotes: 'This is the investors primary entity that they will invest through. Also their primary business.'},
        {investor_id: 17, name: 'Daniel Rand', address: '6516 Lincoln Dr', city: 'Philadelphia', state: 'DescriptionPennsylvania', contactNumber: '777-777-7777', mobileNumber: '777-777-7777', entityNotes: 'This entity is through them personally, not any other company'},
        {investor_id: 17, name: 'Iron Fist', address: '6516 Lincoln Dr', city: 'Philadelphia', state: 'DescriptionPennsylvania', contactNumber: '777-777-7777', mobileNumber: '777-777-7777', entityNotes: 'This is the investors primary entity that they will invest through. Also their primary business.'},
        {investor_id: 18, name: 'Frank Castle', address: '12 Oakridge Dr', city: 'Huntington', state: 'New York', contactNumber: '888-888-8888', mobileNumber: '888-888-8888', entityNotes: 'This entity is through them personally, not any other company'},
        {investor_id: 18, name: 'Punisher Inc.', address: '12 Oakridge Dr', city: 'Huntington', state: 'New York', contactNumber: '888-888-8888', mobileNumber: '888-888-8888', entityNotes: 'This is the investors primary entity that they will invest through. Also their primary business.'},
      ]);
    });
};
